### ISSUE TITLE
Still can't do anything with this

### ISSUE THREAD

**Issue by broyuken** [gcobb321/icloud3_v3#29] opened 2023-01-13 20:17 UTC
I have the newest release version installed, but when I go to update device in the menu, I get "Unknown error occurred" No errors in the logs, but I can't do anything.

**Comment by gcobb321** [comment] 2023-01-14 06:15
I ran into this today and am rewriting a few things. I thought I had it fixed since I could not reproduce the errors. It has to do with requesting the device info from iCloud for the famshr device selection list. That has already been done during startup but that info has not been saved and was falling on the second request. I hope to get the new code done today.

**Comment by gcobb321** [comment] 2023-01-14 18:38
I just uploaded beta which takes a completely different approach to the problem. I'm hoping it was fixed in beta 8. Let me know if it was fixed or is still a problem.

**Closed** 2023-01-14 18:42 UTC
