### ISSUE TITLE
Unable to save on "Tracking & Other Parameters": missing event log resources directory

### ISSUE THREAD

**Issue by serin113** [gcobb321/icloud3_v3#255] opened 2024-01-17 09:14 UTC
Selecting the "save" option and submitting doesn't go back to the main menu: it only fails silently, with an Error 400 (Bad Request) appearing in the console.

(Of note, it also failed to copy the event files from `custom_components/icloud3/event_log_card/` to `custom_cards/`, requiring a manual copy.)

![image](https://github.com/gcobb321/icloud3_v3/assets/1628474/bc17ec90-a46c-40a9-9670-05829a867f60)

The "Event Log Card Lovelace Resources Directory" dropdown is highlighted red, and there are no selectable options.

![image](https://github.com/gcobb321/icloud3_v3/assets/1628474/ca8fcf4d-98ae-461b-9831-823cc2adf67e)

My configuration file in `.storage` has the following section:
```
"profile": {
    "version": 1,
    "ic3_version": "3.0.rc9",
    "version_install_date": "2024-01-17 16:20:18",
    "config_update_date": "2024-01-17 16:48:25",
    "event_log_card_directory": "www/icloud3",
    "event_log_card_program": "icloud3-event-log-card.js",
    "event_log_btnconfig_url": "",
    "event_log_version_running": "",
    "event_log_version": "3.0.16"
},
```

The event log loads fine though, with `/local/custom_cards/icloud3-event-log-card.js` added to the dashboard resources.

![image](https://github.com/gcobb321/icloud3_v3/assets/1628474/ffdc695b-e47d-42e6-b415-c218fe18561a)

So far this issue prevents me from modifying the tracking settings from the UI; I tried resetting iCloud3_v3 by removing the integration, deleting these directories
- `.storage/icloud`
- `.storage/icloud3`
- `www/icloud3`

then restarting HA, adding the integration from HACS again, to no avail.

**Comment by gcobb321** [comment] 2024-01-17 09:49
The directories you deleted were the iCloud token and cookies used for logging into your iCloud account, the iCloud3 configuration files so you will/May have to reconfigure iCloud3 again and the file with the Event Log which will probably be recreated. 

I see you are running HA on some type of setup with everything in the _/home/homeassistant/.homesssistant_ directory structure. That is what it’s probably causing the _Event Log_ directory not populating in the config screen. It is looking for on that starts with _config_. I’m running on a RPi. 

Also, your config file has the directory under the _www_ directory as _icloud3_ but you manually copied it to the _custom_cards_directory like it was in v2. It’s the _”event_log_card_directory": "www/icloud3",_ parameter. 

When you start iCloud3 again, it will create the config file again. It will also create the www/icloud3 directory. It will check the Lovelace resources and you will probably have to change that manually to match your directory structure.

**Comment by gcobb321** [comment] 2024-01-17 20:34
I have updated iC3 to take the HA system config directory structure into consideration when populating:
- the list of www directories for selecting the EvLog .js location
- device's pictures in the www directory and it's sub-directories.
Attached is the rc10 zip file. Unzip it into the icloud3 directory and restart ha.

Other changes include:
1. NEARBY DEVICES - Changed the distance to another device routine so it would not calculate the distance to 'itself', which is always 0.
2. WAZE HISTORY MAP - Fixed a problem displaying the Waze History gps locations on a map.
3. MOBILE APP INTEGRATION - A check for the Mobile App Integration installation will now be done when setting up the iOS App devices and, if the Mobile App setup had not be completed, again after HA had finished starting up.
4. HA ZONE UPDATES - When a one is added, deleted or updated, iCloud3 needed to be restarted to load the new zone settings. This is not longer needed. iCloud3 will update the zone settings when they are made or on the next location update.
5. IOS APP --> MOBILE APP - All references to 'iOS App' have been changed to 'Mobile App' for consistence with HA.

I had planned on releasing this today but will hold off to make sure it works on your system. Let me know if you run into anything or if everything is OK.

Gary

[icloud3_v3-rc10.zip](https://github.com/gcobb321/icloud3_v3/files/13968508/icloud3_v3-rc10.zip)

**Comment by serin113** [comment] 2024-01-18 05:36
> I see you are running HA on some type of setup with everything in the _/home/homeassistant/.homesssistant_ directory structure. That is what it’s probably causing the _Event Log_ directory not populating in the config screen. It is looking for on that starts with _config_. I’m running on a RPi.

I'm running an [HA Core](https://www.home-assistant.io/installation/linux#install-home-assistant-core) installation on Armbian (OrangePi One), the installation folders seem to be different.
____
I removed the integration, deleted the configuration files with `www/custom_cards` and `www/icloud3`, removed the `icloud3-event-log-card.js` resource from lovelace, then added the `rc10` files and re-added the integration.

Without going through the iCloud login process (only adding the integration), what happened is:
- It added an `icloud3-event-log-card.js` resource that doesn't load
  - Loading `/local/icloud3/icloud3-event-log-card.js` instead works though, so the files do get copied automatically there. The logs show:

    ```
    Copied From - /config/.../icloud3/event___log_card/
    Copied To.... - /home/homeassistant/.homeassistant/www/icloud3/
    ```
- The configuration file seems to be missing where the event log card files are: not sure if I missed something in the process of adding the integration.

  ```
  "profile": {
        "version": -1,
        "ic3_version": "3.0.rc10",
        "version_install_date": "2024-01-18 13:13:11",
        "config_update_date": "2024-01-18 13:13:21",
        "event_log_card_directory": "www/icloud3",
        "event_log_card_program": "icloud3-event-log-card.js",
        "event_log_btnconfig_url": "",
        "event_log_version_running": "",
        "event_log_version": "Not Installed"
    },
    ```
- The *Tracking & Other Parameters* screen still doesn't show any option in the "Event Log Card Lovelace Resources Directory", which is still highlighted red, and still preventing changes.
![image](https://github.com/gcobb321/icloud3_v3/assets/1628474/cfe291b0-f436-4fba-a375-7f2441708702)


The folders detected, from the log:
- Base Config Directory: `/home/homeassistant/.homeassistant`
- iCloud3 Directory: `/home/homeassistant/.homeassistant/custom_components/icloud3`
- iCloud3 Configuration File: `/home/homeassistant/.homeassistant/.storage/icloud3/configuration`

**Comment by gcobb321** [comment] 2024-01-18 10:25
I was testing it in a docker test setup where the directories are something like _ha_dev/workspaces/config/www/icloud3/_.  I’ll create your structure and retry it. The device picture setting on the Update Devices screen is also affected. It does a scan of the /www directors looking for .jog and .png files. 

Before, _/config_ was hard coded for the Base Directory instead of seeing what it really was.  
Your iCloud3 config is good. The evlog .js file directory is “base_config_directory” +  the "event_log_card_directory": "www/icloud3", parameter. I’m wondering if the problem is 2 ‘/‘s or none between the base and evlog directory bands when it gets built. I’ll also put some Debug statements in and send you later.

**Comment by serin113** [comment] 2024-01-18 11:42
> The _copied from _statement shows ‘config’ on the displayed line. I haven’t looked at the code yet but was a BaseDir/config/www/icloud3’ created?

The base directory (I'm assuming it's `/home/homeassistant/.homeassistant`) doesn't have any `config` folder created:

![image](https://github.com/gcobb321/icloud3_v3/assets/1628474/6e3f4da8-fe8a-47dd-a620-8f3270fe8f69)

Only two folders have the `icloud-event-log-card.js` and adjacent files:
- `/home/homeassistant/.homeassistant/custom_components/icloud3/event_log_card/`
- `/home/homeassistant/.homeassistant/www/icloud3/`

Maybe the `/config/...` part of the path is referring to `/home/homeassistant/.homeassistant`?

**Comment by gcobb321** [comment] 2024-01-18 11:44
It’s probably just part of the message being displayed

**Comment by gcobb321** [comment] 2024-01-18 14:42
Unzip config_flow.zip into the icloud3 directory. It will dump file-directory info to _icloud3-0.log' as the EvLog and DevicePicture lists are built when you go to the Tracking Parameters and Update Device screen

[config_flow.zip](https://github.com/gcobb321/icloud3_v3/files/13977900/config_flow.zip)

```
2024-01-18 09:30:43 [config_flow.:3401]  ::::::::: WWW PICTURE DIRECTORY > Level-4, FullPath-/workspaces/ha_core_dev/config/www,
2024-01-18 09:30:43 [config_flow.:3401]  ::::::::: WWW PICTURE DIRECTORY > Level-5, FullPath-/workspaces/ha_core_dev/config/www/.history,
2024-01-18 09:30:43 [config_flow.:3401]  ::::::::: WWW PICTURE DIRECTORY > Level-6, FullPath-/workspaces/ha_core_dev/config/www/.history/custom_cards,
2024-01-18 09:30:44 [config_flow.:3401]  ::::::::: WWW PICTURE DIRECTORY > Level-5, FullPath-/workspaces/ha_core_dev/config/www/custom_cards,
2024-01-18 09:30:44 [config_flow.:3410]  ::::::::: WWW PICTURE FILE > www/custom_cards/garage-door-closed.png,
2024-01-18 09:30:44 [config_flow.:3410]  ::::::::: WWW PICTURE FILE > www/custom_cards/garage-door-open.png,
2024-01-18 09:30:45 [config_flow.:3410]  ::::::::: WWW PICTURE FILE > www/custom_cards/ipad.png,
2024-01-18 09:30:45 [config_flow.:3410]  ::::::::: WWW PICTURE FILE > www/custom_cards/watch-dark.png,
2024-01-18 09:30:45 [config_flow.:3410]  ::::::::: WWW PICTURE FILE > www/custom_cards/watch-light.png,
```

and
```
2024-01-18 09:30:21 [config_flow.:1411]  ::::::::: WWW DIRECTORY LIST > FullPath-/workspaces/ha_core_dev/config/www, SubDir-www, Level-4,
2024-01-18 09:30:22 [config_flow.:1411]  ::::::::: WWW DIRECTORY LIST > FullPath-/workspaces/ha_core_dev/config/www/.history, SubDir-www/.history, Level-5,
2024-01-18 09:30:22 [config_flow.:1411]  ::::::::: WWW DIRECTORY LIST > FullPath-/workspaces/ha_core_dev/config/www/.history/custom_cards, SubDir-www/.history/custom_cards, Level-6,
2024-01-18 09:30:22 [config_flow.:1411]  ::::::::: WWW DIRECTORY LIST > FullPath-/workspaces/ha_core_dev/config/www/custom_cards, SubDir-www/custom_cards, Level-5,
```

**Comment by serin113** [comment] 2024-01-18 19:16
The directory listings had these paths:
```
2024-01-19 02:45:12 [config_flow.:1411]  ::::::::: WWW DIRECTORY LIST > FullPath-/home/homeassistant/.homeassistant/www, SubDir-www, Level-4,
2024-01-19 02:45:12 [config_flow.:1411]  ::::::::: WWW DIRECTORY LIST > FullPath-/home/homeassistant/.homeassistant/www/icloud3, SubDir-www/icloud3, Level-5,

...

2024-01-19 02:58:39 [config_flow.:3401]  ::::::::: WWW PICTURE DIRECTORY > Level-4, FullPath-/home/homeassistant/.homeassistant/www,
2024-01-19 02:58:39 [config_flow.:3401]  ::::::::: WWW PICTURE DIRECTORY > Level-5, FullPath-/home/homeassistant/.homeassistant/www/icloud3,
```

(I excluded the folders for other HACS components in the listings)

There were no `WWW PICTURE FILE` lines in the log, even though the PNG files were copied to `/home/homeassistant/.homeassistant/www/icloud3` (not under a `custom_cards` folder though):

![image](https://github.com/gcobb321/icloud3_v3/assets/1628474/fc410e8b-b209-4427-87c5-2c28c09780d7)

**Comment by gcobb321** [comment] 2024-01-18 22:31
I found a filter I didn't like and reworked it a bit. I built your Base directory structure inside my /config directory and all appeared OK. 

The traces are still there to add debug info to the icloud3-0.log file. The lists are build when you go to the screen so you have to go to the Tracking Parameters and into the Update Devices screens.

Unzip and restart HA
[config_flow.zip](https://github.com/gcobb321/icloud3_v3/files/13982229/config_flow.zip)

**Comment by serin113** [comment] 2024-01-19 03:48
The picture files were successfully listed this time:

```
2024-01-19 11:37:25 [config_flow.:3401]  ::::::::: WWW PICTURE DIRECTORY > Level-4-0, FullPath-/home/homeassistant/.homeassistant/www, FilterCnt-0,
2024-01-19 11:37:25 [config_flow.:3401]  ::::::::: WWW PICTURE DIRECTORY > Level-5-0, FullPath-/home/homeassistant/.homeassistant/www/icloud3, FilterCnt-0,
...
2024-01-19 11:37:25 [config_flow.:3408]  ::::::::: WWW PICTURE FILE > www/icloud3/garage-door-open.png,
2024-01-19 11:37:25 [config_flow.:3408]  ::::::::: WWW PICTURE FILE > www/icloud3/airpods.png,
2024-01-19 11:37:25 [config_flow.:3408]  ::::::::: WWW PICTURE FILE > www/icloud3/watch-light.png,
2024-01-19 11:37:25 [config_flow.:3408]  ::::::::: WWW PICTURE FILE > www/icloud3/garage-door-closed.png,
2024-01-19 11:37:25 [config_flow.:3408]  ::::::::: WWW PICTURE FILE > www/icloud3/ipad.png,
2024-01-19 11:37:25 [config_flow.:3408]  ::::::::: WWW PICTURE FILE > www/icloud3/watch-dark.png,
...
2024-01-19 11:37:31 [config_flow.:1412]  ::::::::: WWW DIRECTORY > www, Level-0-0, FullPath-/home/homeassistant/.homeassistant/www, FilterCnt-0,
2024-01-19 11:37:31 [config_flow.:1412]  ::::::::: WWW DIRECTORY > www/icloud3, Level-1-0, FullPath-/home/homeassistant/.homeassistant/www/icloud3, FilterCnt-0,
...
```

And the dropdown now shows the event log card directory (and other folders):

![image](https://github.com/gcobb321/icloud3_v3/assets/1628474/bf45756c-54cb-4c2d-8402-aac80b3e1e13)

**Comment by JtwoA** [comment] 2024-01-19 05:34
[image.png]

After updating to 10 just now.

**Comment by gcobb321** [comment] 2024-01-19 07:08
@serin113 
Prefect

**Comment by gcobb321** [comment] 2024-01-19 19:32
@JtwoA @serin113

Here is the latest rc10 with fixes for the issues above..
[icloud3_v3-rc10.zip](https://github.com/gcobb321/icloud3_v3/files/13993668/icloud3_v3-rc10.zip)

**Comment by serin113** [comment] 2024-01-20 11:32
> Here is the latest rc10 with fixes for the issues above.. [icloud3_v3-rc10.zip](https://github.com/gcobb321/icloud3_v3/files/13993668/icloud3_v3-rc10.zip)

The fix works: it now shows `www/icloud3` in the dropdown.

As for the entry being added to the Lovelace resources (`icloud3-event-log-card.js`, not under a folder) not working, the only way to load it at the moment is by using `/local/icloud3/icloud3-event-log-card.js`.

There's a way to use a `/hacsfiles/` path instead for [HACS installations](https://hacs.xyz/docs/categories/plugins/), but it might be specific to Frontend plugins.

**Comment by gcobb321** [comment] 2024-01-20 18:00
OK, this should do it. When you change the EvLog directory in Config Settings, the Lovelace resource is updated if it exists and added if it does not exist. I also verified the the EvLog source from the icloud3 directory is copied to the new directory if it needs to be.

[icloud3_v3-rc10.zip](https://github.com/gcobb321/icloud3_v3/files/13998750/icloud3_v3-rc10.zip)

**Comment by serin113** [comment] 2024-01-20 18:55
> OK, this should do it. When you change the EvLog directory in Config Settings, the Lovelace resource is updated if it exists and added if it does not exist. I also verified the the EvLog source from the icloud3 directory is copied to the new directory if it needs to be.
> 
> [icloud3_v3-rc10.zip](https://github.com/gcobb321/icloud3_v3/files/13998750/icloud3_v3-rc10.zip)

I tested this by removing the card from the resources, creating a new empty folder `www/icloud3_customtest`, selected it as the new EvLog directory, then restarted HA.

Once HA completed startup, the event log card didn't need to be added to the resources manually: it successfully copied over the card files into `www/icloud3_customtest` and added the resource with the path `/local/icloud3_customtest/icloud3-event-log-card.js`, and a refresh loaded the card from the new folder.

![image](https://github.com/gcobb321/icloud3_v3/assets/1628474/112640fa-eb22-4fa3-ba4e-dcfc85057c28)

**Comment by gcobb321** [comment] 2024-02-26 16:48
Closing this issue with the release of v3.0

**Closed by gcobb321** 2024-02-26 16:48 UTC
