### ISSUE TITLE
"Unknown error" when trying to update device 

### ISSUE THREAD

**Issue by cedricdelecole** [gcobb321/icloud3_v3#381] opened 2024-12-11 12:42 UTC
Hi there, I am trying to update one of my 2 Apple devices from the config, but getting an "Unknown error" when pushing the submit button ... What could be the issue here ?

![image](https://github.com/user-attachments/assets/4cdb5a85-0b95-482b-b555-90819adebdf5)

I am running 3.0.5.8

P.S. those 2 devices are showing on the map sometimes with 2 hours "next update", and this is what I would like to change by updating the device as I find it annoying.
Many thanks !!

**Comment by gcobb321** [comment] 2024-12-23 15:29
Fixed in v3.1.4 (12/23/2024)

**Closed by gcobb321** 2024-12-23 15:29 UTC

**Comment by cedricdelecole** [comment] 2024-12-23 15:38
Thank you @gcobb321 , but we had to roll bak to previous version Linked to apple account issue ... is 3.1.4 reliable now ??

**Comment by JtwoA** [comment] 2024-12-23 15:40
> Thank you @gcobb321 , but we had to roll bak to previous version Linked to apple account issue ... is 3.1.4 reliable now ??

Reliable?

I can verify it is working as intended.  It's been on my system since mid-day yesterday so it's a little much to use the word "reliable" as that implies performance over a long period of time.  It's working great so far, no issues.

**Comment by gcobb321** [comment] 2024-12-23 15:41
I've been running it for 2-weeks or so and i sent it out as a Sneak Peak to 2-users yesterday. They installed it without any issues. I hope so but...

**Comment by cedricdelecole** [comment] 2024-12-23 15:48
That is ok but I was just not informer that version 3.1.4, which was released to soldve a change at Apple side related to authentication, which was then broken by another change at Apple side, is now back on track ??

**Comment by gcobb321** [comment] 2024-12-23 15:54
From the v3.1.4 Change log in the update announcement issue:

_APPLE ACCOUNT PASSWORD AUTHENTICATION:
Reverted back to the old password authentication protocol before the Secure Remote Password (SRP) protocol was implemented
The Password SRP protocol will be tried if the old password authentication protocol fails._

It uses the v3.1.5.9 method of password verification as it's primary method (pre-October Apple Change). If that fails, the Password SRP method (what Apple used in October-November) is used. This method also works again.

**Comment by JtwoA** [comment] 2024-12-23 16:01
> That is ok but I was just not informed that version 3.1.4, which was released to solve a change at Apple side related to authentication, which was then broken by another change at Apple side, is now back on track ??

Please take the time to read the release notes.  It is a courtesy to the coder who took the time to write them and typically answers (as it does yours) most questions you'll have for the deployment.

**Comment by cedricdelecole** [comment] 2024-12-23 16:23
Oh ... ok, super thanks. I will upgrade then !
