### ISSUE TITLE
from v2.4 to v3 - add device  -> unknown error occurred

### ISSUE THREAD

**Issue by Saesh123** [gcobb321/icloud3_v3#207] opened 2023-09-26 19:27 UTC
Hi, I tried to migrate from v2.4 to v3, but unfortunately the wizard does not find any devices. My Apple ID was accepted and the token was also accepted. What else can I check? I have deactivated the entry in config.yml.
In v2.4 everything worked so far.

<img width="569" alt="Bildschirmfoto 2023-09-26 um 21 14 15" src="https://github.com/gcobb321/icloud3_v3/assets/55209728/d07e8f8b-a891-48a2-9744-753b4a5bff26">

**Comment by gcobb321** [comment] 2023-09-26 20:07
For some unknown reason, the devices did not migrate. There was a problem on this screen when the device list was empty.  It was fixed in Prerelease Version pr1.4 that I uploaded a few days ago. 

Are you running pr1.4 or an earlier. If earlier, install pr1.4 and then add the devices manually. Adding them manually is a simple and quick process. If you are running pr1.4 and got this message, go to _Configure Settings > Page 2 > Format Parameters_ screen, set the log level to Debug, auto reset, restart HA, go back to this _Configure Settings > Update Devices_ screen, get the error and email the _icloud3-0.log_ file to geekstergary@gmail.com so t can see what is causing the error. 

Thanks and hope the pr1.4 works out for you.

**Comment by strfn** [comment] 2023-09-26 22:37
I happen to seem to be affected by the same issue even using pr1.4.
Logs sent via email.

**Comment by gcobb321** [comment] 2023-09-27 08:54
The version of iCloud3 that you are running is in several places:
- The _Event Log_ shows a lot of info when iCloud3 starts. The first and last line of the startup process is:
        _Initializing iCloud3 v3.0.pr1.3 > Tuesday, Sep 26_
- The first line of the icloud3-0.log file is: 
        _2023-09-27 00:00:02 [icloud3_main:1448]  iCloud3 v3.0pr1.3, Log File: Wednesday, 2023-09-27 00:00:02_
- The attributes of the devices being tracked which you can not see since you are having a problem setting them up

**Comment by gcobb321** [comment] 2023-09-27 09:10
This has been fixed in the latest Prerelease Version pr1.4.

There have been several people who have tried to install this version using HACS but have had problems where the pr1.4 version is not installed after they go through the HACS update process and restarting HA. The old pr1.3 version still loads. 

If you have tried to do the HACS update and it does not work, you may have to install it manually by downloading the _icloud3.zip_ file and unzipping into the icloud3 directory. Instructions on how to do that are in the iCloud3 User Guide [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/0.1-migrating-v2.4-to-v3.0?id=hard-way-but-not-too-hard-manual-installation)

**Comment by strfn** [comment] 2023-09-30 21:32
Confirmed that the manual installation worked.

**Comment by gcobb321** [comment] 2023-09-30 23:14
Good. I’ve posted pr1.5 to the development repository and will be doing an update later the week. I’m hoping that HACS install works correctly.

**Closed** 2023-10-06 09:01 UTC
