### ISSUE TITLE
"None" error

### ISSUE THREAD

**Issue by mobiledude** [gcobb321/icloud3_v3#24] opened 2023-01-03 19:16 UTC
getting the following error on my setup. Home Assistant 2023.1.0b5
Latest icloud3_v3 version

```
Deze fout is ontstaan door een aangepaste integratie.

Logger: icloud3
Source: custom_components/icloud3/support/event_log.py:328
Integration: iCloud3 Device Tracker (documentation, issues)
First occurred: 12:05:07 (11 occurrences)
Last logged: 16:47:39

None
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/event_log.py", line 328, in update_event_log_display
    self.evlog_attrs['fname']      = self.fname_selected = self.devicename_by_fnames[devicename]
KeyError: None
```

**Comment by gcobb321** [comment] 2023-01-03 20:24
Get b6 or b7 preliminary and try that version

**Comment by derekoharrow** [comment] 2023-01-03 21:22
This is happening to me in b6. Will try b7

**Comment by derekoharrow** [comment] 2023-01-03 21:49
I can confirm that this seems to be fixed in b7.

**Comment by gcobb321** [comment] 2023-01-03 23:00
I did make as change in b7 to also check for devicename=None. Before it was just checking for devicename=‘’. 
Now it checks for both.

**Closed by gcobb321** 2023-01-03 23:00 UTC
