### ISSUE TITLE
Device Tracker State

### ISSUE THREAD

**Issue by scotty1395** [gcobb321/icloud3_v3#65] opened 2023-02-10 05:44 UTC
The device_tracker states use the friendly name for the state rather than the proper state name. This can cause issues when using the visual editor for automations.

For example, iCloud3 sets the state of the device_tracker to Away.
When creating an automation the visual editor has the friendly name of Away as an option, but actually uses the state of not_home.
Automation doesn't get triggered as iCloud3 doesn't set the device_tracker state to not_home.

**Comment by gcobb321** [comment] 2023-02-10 07:53
See iCloud3 configuration > Event Log Parameters > Device tracker entity HA entity override parameter. Set to off.

**Comment by scotty1395** [comment] 2023-02-13 01:58
Thanks Gary.
Changed that setting and the state is being set as the non-friendly name now, however the zone trigger is still not being triggered in the automation. So it must be something else.

I have a person entity with the iCloud3 device_tracker as it's only tracked device.
The automation is set to trigger when the person entity exits a zone.
When you exit the zone the person state changes but the zone exit trigger is not set off.

The only difference I can see between v2 and v3 is that on v2 the GPS coordinates show as two decimal places in more info / attributes, rather than lots of decimal places with v3.
Under Developer Tools / States, the GPS coordinates show lots of decimal places with both v2 and v3.

**Comment by gcobb321** [comment] 2023-02-13 02:13
If the ic3 d_t state value changes correctly which changes the person correctly but HA does not catch the change and issue the trigger based on the person, it’s probably a HA timing issue, not an ic3 issue.  I would not use the person as the trigger entity. I use the sensor.[devices]_zone_name as my triggers, not the d_t or person. I actually don’t use person at all.  I like the friendly name on the d_t entity. the sensor zone_name is under ic3 control, not HA control so I know what’s going on.

**Comment by scotty1395** [comment] 2023-02-13 02:44
OK. I realise I can work around it in different ways, but it is a regression from v2 behaviour.

**Comment by scotty1395** [comment] 2023-02-14 06:59
Here is what I'm seeing for the decimal places using the app device tracker and then the iCloud3 v3 device tracker against the person entity.
v2 does the same as the HA App example.

![image](https://user-images.githubusercontent.com/56659709/218661701-0c59323a-1896-442b-9068-198e60581aaa.png)

**Comment by scotty1395** [comment] 2023-02-14 22:40
Thanks Gary.

No, not wondering why the iOS and iCloud3 gps is different. I'm wondering why iCloud3 v3 seems to _**always**_ ignore the iOS data. This was not the case in v2.

The screenshots above are to illustrate that v3 is setting the device tracker location somehow differently to how v2 did and how the HA app does. The two more info entities shown are the same entities as to their left. For some reason the HA App (and v2) more info rounds to two decimal places, while the v3 more info does not, while dev tools / states always show the unrounded coordinates. I'm not sure if the rounding itself is causing v3 not to correctly trigger zone entry/exit triggers for HA, or another underlying difference in how v3 is updating the device tracker location compared to v2.

**Comment by gcobb321** [comment] 2023-02-14 23:15
I am not having any problems with iOS app triggering events, that I know of. 
 
So I need detailed logs from v2 and v3 to see what you are seeing. Just seeing a screenshot May identify the problem but I’m going to need some raw data to see what is going on.  I assume you are running them in parallel on different computers or in virtual environments where v2 and v3 are tracking the same devices at the same time so the updates on both should be the same. 

1. Set log level Debug in both v2 and v3.. 
2. In v3, delete the `icloud3-debug.log` file before the reboot. 
3. On both, delete the ‘home-assistant.log‘ files so I don’t have to go through a lot of old data. 
4. Restart HA so both v2 and v3 are starting fresh. Let everything run until you are sure the problem has occurred for a while.
5.  Email me the iCloud3-debug.log and home_assistant.log files. 
6. You can also do a Event Log > Actions > Export Event Log on both v2 and v3. 
7. Identify some of the triggers on v2 that should show up on v3 but aren’t. They should be on the Event Log. That way I can look at the raw data in v2 and compare it to v3 from the same time period when the problem is occurring. I’ll have a lot of data to look at and will try to see what you are seeing. 

Thanks. 
Gary

**Comment by scotty1395** [comment] 2023-02-15 00:51
Thanks Gary.

Sorry, I don't currently have a second environment to test in parallel. I've been manually changing between v2 and v3. I'll see what I can set up.

Version 2 and version 3 screenshots below for coordinate rounding comparison.
I'll turn on the Show Tracking Monitors to see what it reveals.
I'm tracking two devices.

Just so we're on the same page...

- iOS app is correctly triggering iCloud3 events. The problem is iCloud3 seems to always be ignoring the iOS app location data and only getting location data from iCloud. (Other issue - #68 )
- Separate to that issue, HA automation zone entry/exit triggers are not firing due to how v3 is updating the device tracker entity compared to how v2 does. (This issue - #65 )

Dev tools > states screenshot, iCloud3 v2 and HA App, which both work with HA automation zone entry/exit triggers
![image](https://user-images.githubusercontent.com/56659709/218890277-83abb144-4e15-47d3-8df8-137b19552c73.png)

More info screen shots of the same entities at the same time with rounded coordinates
`device_tracker.brads_iphone`
![image](https://user-images.githubusercontent.com/56659709/218890650-745bb173-c271-42fc-a4ce-2a813f904dba.png)

`device_tracker.brads_iphone_2`
![image](https://user-images.githubusercontent.com/56659709/218890967-92e28226-d26a-4d91-9233-79ddc9dbeb9a.png)


Dev tools > states screenshot, iCloud3 v3 and HA App, iCloud3 v3 doesn't work with HA automation zone entry/exit triggers
![image](https://user-images.githubusercontent.com/56659709/218895964-6ddaade8-c36d-4ff9-8d0c-7c550eafa7ba.png)

More info screen shots of the same entity at the same time with iCloud3 non-rounded coordinates
![image](https://user-images.githubusercontent.com/56659709/218896214-927154c8-e2bf-4036-a9f3-5fc293fb3c8e.png)

**Comment by gcobb321** [comment] 2023-02-15 04:46
There has to be a setup issue with the iOS app if you are never getting triggers and location updates from the iOS app. Send me the iCloud-debug.log file (geekstergary@gmail.com) to see what you r set up is. Also send me an Event Log > Actions > Export Event Log of v3. Set log level to raw data to show what is being picked up by the iosapp sensors iCloud3 is monitoring. 

And go to the Update iCloud3 Devices configuration screen and look at the iOS app monitor device assignment. You can set to a specific iOS app device or scan for one starting with the FamShr device name. Select the actual device to monitor, not the scan selection. 

About the gps 2-decimal places in v2, I haven’t changed v2 since Dec2021 so I guess it’s always been that way.. I can only make sure v3 is filling in its d_t and sensor entities correctly. Which it looks like it is. How person handles it is out of my control if the gps in the d_t attributes are correct.

**Comment by scotty1395** [comment] 2023-02-15 04:58
I've done a clean install of v3 without upgrade. Will monitor what it does over the next few days.
The monitor device assignment is set to the specific devices, so that's ok.

With the decimal places, is v2 using a different method to update the device_tracker compared to what v3 is doing?
How person and device_tracker handles it is out of your control, but it is handling the way v2 updates it correctly and failing with v3.

**Comment by gcobb321** [comment] 2023-02-15 11:20
Everything is different between v2 and v3. V2 creates all the d_t and sensor entities as temporary ones where v3 is a true Integration that creates permanent ones using HA standard methods where they are added to the HA entity registries.

 Maybe by changing back and forth, the person is tracking the v2 entity, not the v3 one. The person i is set up in the core/. Storage/person file. It has the d_t entities assigned to that person. The device_registry and entity_registry also have the dt name. When an entity is added, HA will add a suffix to it and use that name internally instead on the first one you entered. Maybe the person  has the v2 name, not the v3 one. Look in those registry files for the v3 name and see if that is the case. Set up a new person when v3 is running and see what it follows.

**Comment by scotty1395** [comment] 2023-02-15 22:51
My person entity is set up correctly. It is really related to the iCloud3 device tracker entity because an automation with zone trigger looking directly at that has the same result.

I'm not sure I can do anything more from my end.
If you're so inclined, it should be straightforward to reproduce the problem on your end. You just need a simple automation with a zone trigger looking at the iCloud3 device tracker.

**Comment by gcobb321** [comment] 2023-02-15 23:08
I would be glad to try to reproduce the problem on my end but I need you send me the yaml code for your automations that show what is not working. It would be futile and time consuming for me to try to guess what you are seeing/using try to recreate the problem when I really do not know what it is and still not get it.  I do have a lot on my plate and guessing is not a good use of my time.

The device tracker entity state value has 2 options- the actual HA zone entity name and a Friendly Name that is either the HA zone friendly name or a reformatted name. I need to know exactly what you want it to be if that is not enough. Otherwise, I'm sure that you will be changing your automation triggers to use what iC3 is providing.

**Comment by scotty1395** [comment] 2023-02-15 23:22
I've tried both options for the device tracker entity state with the same result.

Here's an example automation that fails to trigger with v3. Works fine with v2:

```
alias: iCloud3 Zone Test
description: ""
trigger:
  - platform: zone
    entity_id: device_tracker.brads_iphone
    zone: zone.home
    event: enter
condition: []
action:
  - service: notify.mobile_app_brads_iphone_2
    data:
      message: Welcome home
mode: single
```

**Comment by broyuken** [comment] 2023-02-20 16:19
I’m seeing similar issues with my setup. If I set it to use the HA name, then if I go to a zone called store the state will be “store” but the zones display name would be “Store” and wouldn’t match. If I set it to the Formatted name, then Store will be “Store”, but then my home zone gets messed up. The home state would be “Home” but the state that my house is expecting would be “home”. This worked fine under v2 but does not work in v3. It’s almost like we need to set the state to lowercase but display the state in cards in uppercase, or use the friendly name for displays.

**Comment by gcobb321** [comment] 2023-02-20 16:28
Go to developer tools and look at device tracker state. What are for the iCloud3 and iOS app values? Upper case, lower case, both different. I can force to lower state if HA zone entity  I have seen home (lower) as the state value but display as Home (upper). But other zones have state value as lower (store) and display as lower (store). I’m not sure what HA is doing. See if it makes sense for you.

**Comment by gcobb321** [comment] 2023-02-20 22:53
I did a lot of errands today and monitored the device_tracker state in the developer tools screen, what was displayed on the icloud3 screen and in the Attributes section of the device_tracker entity. From what I can tell, iCloud3 is setting the d_t state value to the zone.zone entity name for the various zones, not the friendly_name or anything else. Attached are screen captures for you to compare to what you are seeing. I have the iC3 > Configurator > Event Log Parameters > Device_tracker set to HA zone entity name.
![evlog_config](https://user-images.githubusercontent.com/35449479/220209531-8414e4d7-5f36-457a-9d5b-02db7e73b71c.png)
![home](https://user-images.githubusercontent.com/35449479/220209611-ee59818b-a7ab-48ca-9c95-7a987bbad19f.png)
![away](https://user-images.githubusercontent.com/35449479/220209625-65a7f668-490c-4298-8d22-60548676d68c.PNG)
![publix](https://user-images.githubusercontent.com/35449479/220209628-d366d8bd-22d2-42ca-805d-156969c01375.PNG)
![warehouse](https://user-images.githubusercontent.com/35449479/220209629-18381acc-bc2d-4567-85d1-a5287c992efe.PNG)
![ind_riv_shores](https://user-images.githubusercontent.com/35449479/220209630-bc2a33e1-7f5e-435d-80f0-a622bd7719a5.PNG)

**Comment by broyuken** [comment] 2023-02-20 23:48
Yes that matches what I see as well, but now create an automation for when you enter or leave a zone. It is looking for Warehouse or Publix MM, etc, not the lowercase values so it doesn’t trigger.

**Comment by gcobb321** [comment] 2023-02-21 01:25
The HA iOS app is using the friendly name as the state as shown in the pics above, not the zone entity name. Maybe HA is looking for a match on the friendly name, not the entity name. Show me you automation that is not triggering, the d_t state and friendly name and the zone entity and friendly name so I can understand the issue and exactly what option you would like the d_t state values to be. 

If you want, send me Automation and the /config/.storage/entity_registry file so I can see exactly what the values in the entity registry file matches to your setup. In the entity registry file, the zone actually has 3 names, the entity name, the name, and the original name.

**Comment by broyuken** [comment] 2023-02-21 02:48
His automation is exactly how mine is set up, just a little more detailed because it’s not a test one. Ill see if I can grab those files soon and see how they look.

**Comment by gcobb321** [comment] 2023-02-21 10:44
I just added a zone - ‘Back in Form’:
- _entity_reg_ -> entity_id=‘back_n_form’, original_name=‘Back in Form’
- _zone_ -> entity_id=‘zone.back_in_form, name=‘Back in Form’

Change the zone name to ‘BackInForm’:
- _entity_reg_ -> no changes
- _zone_ -> name=‘BackInForm’

HA changed the zone file but not the entity reg. 
v2 got the zone’s friendly name from _zone_, v3 gets it from _entity_reg_.
On the _Area & Zone_ screen, it uses names from _zone_
When you list the zones on a name to select from, it shows the _entity_reg_ name.
Looking at the actual code in the _zone_ component _trigger.py_ module, the _friendly name_ comes from _zone_, not the _ent_reg_

This is an inconsistency in HA where it sometimes lists the name from _zone_ and in other places, uses the one from _entity_reg_. I think it is trying to keep them in sync but that does not always happen.

I’ll change it back to the _zone_ file for trigger purposes and maybe show the one from the _entity_reg_ value for list selection purposes on the configuration screens.

**Comment by gcobb321** [comment] 2023-02-22 20:46
I have added some options to the d_t state value (zone entity, friendly name, reformatted iC3 names based on the entity id). The friendly name comes from the zone setup file instead of the entity registry. Plus a lot of other stuff.

Attached is the beta13 preliminary release. See the ChangeLog for a complete list of items. There are some important things in it.

I have looked at the code that generates the zone enter/exit triggers and tried to figure out what ha is doing by following the code in the icloud3 component. I do not think it is looking at the state values but, instead, is looking at the lat/long attributes and then using them to determine if the device is in a zone and then checking to see if the device's zone changed. It then issues a trigger that fires the automation. 

I have set up several automations, selecting a device_tracker entity, a zone and a trigger. My automations do not trigger and never run. I think there are some settings inside ha that need to be set up that I have not figured out. I will continue to look at it but will need to find a better example than the convoluted icloud component, Let me know it something works for you.

Inzip into the iCloud3 directory like you have been doing.
[icloud3_v3-beta-13p4.zip](https://github.com/gcobb321/icloud3_v3/files/10808166/icloud3_v3-beta-13p4.zip)

**Comment by broyuken** [comment] 2023-02-25 01:24
Just tried beta 13 and set the state to the HA Zone Friendly Name used by automation triggers option, but it shows my device_tracker.brians_iphone as Home, whereas my _2 device tracker is home. So it seems like there is still something off with the formatting.

**Comment by gcobb321** [comment] 2023-02-25 07:18
I assume your _2 device is the iOS app device. The iOS app is inconsistent with setting the device_tracker state value for the home zone. It will always display it as `home`. With iCloud3 set to the friendly name, iCloud3 will set it to `Home`. If you move to another zone (entity=cosco, Friendly Name =Cosco), the iOS app displays the friendly name `Cosco`. 

Obviously, I can change the home zone only to always display `home` but was never sure if that was the thing to do since you would then have an inconsistency that may affect others. The `home` could be the friendly name setting by default with another option to set it to `Home`. 

I’ll post a question and see what the response is.

**Comment by broyuken** [comment] 2023-02-25 12:44
Yea the _2 is the iOS app. And I know that’s unaffected by ic3, I was just showing that the iOS app has the “correct” state. When ic3 is set to Home, my person entities are not home and my house shuts down. But when it’s set to home, I am home. 

The issue still is if I have my home set in lowercase, the zone enter/exit automations still fail to trigger. These same automations worked perfectly under ic3_v2

**Comment by gcobb321** [comment] 2023-02-25 14:46
Get beta 13a just uploaded for the `'home` / 'not_home` state value issue. These values are now always used when the Friendly Name is selected so iCloud3 displays the same values as the iOS App.

About the zone enter/leave trigger. I thought I had it figured out and made some code changes but it is going to take some more figuring out what HA is doing. It worked in v2 because v2 was not an integration and all state value updates were handled by HA. As an integration, the updates are handled by iC3.

**Comment by broyuken** [comment] 2023-02-25 15:23
Gotcha, if you have anything we can help with let us know and we’ll help test or whatever you need.

**Comment by broyuken** [comment] 2023-02-25 21:15
At my in laws and the ic3 shows the zone name, and the _2 shows the formatted name 

![3C6A544B-ACE7-44F0-926B-3B356EF917CA](https://user-images.githubusercontent.com/1593391/221379923-e4269c19-0884-4025-af37-f81c1f7a8207.png)

**Comment by gcobb321** [comment] 2023-02-25 21:19
Check configuration settings. Make sure it is friendly name. NoT entity name. What will display shows in Stage 2 off startup log when zones are set up

**Comment by broyuken** [comment] 2023-02-26 03:17
If I set it to friendly name, when I’m home it’s set to Home which makes my person entity not registered as actually being home if that makes sense.

**Closed** 2023-02-28 01:02 UTC

**Comment by gcobb321** [comment] 2023-03-03 21:57
Here is the beta 14. It has not been released yet so be sure to let me know if you run into anything weird.. Unzip into the icloud3 directory. See #3.

Here are all the changes in this beta:
1.  iCloud Account Authentication - When the iCloud Account is verified using a password, a session access 
    token is created and stored as a cookie. The password login also generates an email saying someone has 
    logged into your iCloud account. This beta changes the method of authenticating the account to using 
    the token first and then using the password if it has expired. This should eliminate or greatly reduce 
    the login emails generated by Apple.
2.  Configuration Wizard > iCloud Account Credentials screen - Updated it to improve readability and make 
    it easier to set up the account information. Several rare problems were also fixed where (1) logging 
    into an iCloud Account with an incorrect password would still allow access when there was a valid token 
    and (2) logging into an iCloud Account with a changed password would not work if the token has expired. 
    Now, logging in with a new password causes a new 2fa request to be made.
3.  Zone enter/leave event for an iCloud3 device_tracker entity - This can now be used as an automation 
    trigger.
4.  Latitude/longitude values - They are now stored as numeric fields in the device_tracker attributes instead 
    of a string field. They are now displayed with 2-decimal places on a Lovelace device_tracker/attributes 
    window (an HA limitation). A new gps attribute has been added to display the latitude/longitude with it's 
    full precision.
5.  Passive Zones - Fixed a problem where passive zones could be selected. Also found out that the iOS App 
    will generate enter/exit triggers for passive zones. These will now be ignored by iCloud3.
6.  Configuration Wizard > Sensors screen - Changed it  for readability and to list the important sensors 
    first.
7.  Event Log - Made some minor formatting changes. Also added a new icon to the top-right of the Event Log 
    so you can become an iCloud3 Stargazer. Click it to go to the iCloud3_v2 GitHub repository. Then click 
    the star in the top-right corner.

[icloud3_v3-beta-14.zip](https://github.com/gcobb321/icloud3_v3/files/10886402/icloud3_v3-beta-14.zip)

**Comment by broyuken** [comment] 2023-03-04 14:30
Updated to 14 last night, and this morning my zone entry/exit automation works again! Thanks!

**Comment by gcobb321** [comment] 2023-03-04 14:46
Glad it’s working for you.  I’ve been running with it for a few days. Since there are no HA docs, it took me a while to find a component with the code that was doing it. The base icloud component was no help. Turned out to be very simple and was being done by the mobile_app component. 

b14 messed up the distance precision sensor values for distances less than 1 mile. Will have a fix a little later this morning.

**Comment by gcobb321** [comment] 2023-03-04 18:19
This b14 version addresses sensor precision:
8.  Distance Sensors - (1) Changed the distance precision so the distance value is within 6-inches/
    10-centimeters of the measurement between the device and the zone center. (2) Changed the
    '_moved_distance' sensor to display in feet/meters when less than 1mi/1km. (3) Added moved from time
    and moved to time to the '_moved_distance' sensor.

[icloud3_v3-beta-14.zip](https://github.com/gcobb321/icloud3_v3/files/10889352/icloud3_v3-beta-14.zip)
