### ISSUE TITLE
Apple Account Login Error 503 (Apple Refusing SRP Password)

### ISSUE THREAD

**Issue by spry-salt** [gcobb321/icloud3_v3#375] opened 2024-11-24 07:18 UTC
I've tried deleting all config data and starting from scratch, and I've confirmed I can login to account.apple.com successfully with the credentials I'm using with iCloud3. Here's the debug log:

`11-24 18:13:38 [start_ic3_co:0161] STAGE3 ⡇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                          ⡇    STAGE 3 > DEVICE CONFIGURATION
                                          ⡇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
11-24 18:13:38 [start_ic3_co:0174] STAGE3  Data Sources > iCloud, MobApp
11-24 18:13:38 [pyicloud_ic3:0112] STAGE3  Verify Apple Account Username/Password
11-24 18:13:38 [pyicloud_ic3:0526] STAGE3  MYUSERNAME, Checking Username/Password validity
11-24 18:13:38 [pyicloud_ic3:0202] STAGE3
🔺 MYUSERNAME, POST, REQUEST,  VALIDATE_USERNAME_PASSWORD/541
❗   items={'url': 'setup.icloud.com/setup/authenticate/MYUSERNAME@…………', 'retry': 0, 'data': None, 'json': None}
❗   headers={'Authorization': 'Basic ……5JTkc='}
11-24 18:13:39 [pyicloud_ic3:0259] STAGE3
🔻 MYUSERNAME, POST, RESPONSE, VALIDATE_USERNAME_PASSWORD/541 
❗   items={'code': 409, 'ok': False}
11-24 18:13:39 [pyicloud_ic3:0544] STAGE3  MYUSERNAME, Validate Username/Password Results, Valid-True
11-24 18:13:39 [start_ic3_co:0198] STAGE4 ⡇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                          ⡇    STAGE 4 > DATA SOURCE DEVICE ASSIGNMENT
                                          ⡇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
11-24 18:13:39 [start_ic3_co:0210] STAGE4  Data Source > Apple Account used-True
11-24 18:13:39 [start_ic3_co:0211] STAGE4  Data Source > HA Mobile App used-True
11-24 18:13:39 [pyicloud_ic3:0167] STAGE4  APPLE ACCT SETUP > MYUSERNAME, Step-0, Login Started, PyiCloud=<PyiCloudService: 18:13:00-MYUSERNAME>PyiCloud.is_DeviceSvc_setup_complete=False PyiCloud.DeviceSvc=<PyiCloud.DeviceSvc: 18:13:00-18:13:01-MYUSERNAME>PyiCloud.RawData_by_device_id.values()=dict_values([])
11-24 18:13:39 [pyicloud_ic3:0669] STAGE4  MYUSERNAME, Initialize PyiCloud Service, Set up iCloud Location Services connection
11-24 18:13:39 [pyicloud_ic3:1162] STAGE4  MYUSERNAME, , Session file does not exist (/config/.storage/icloud3.apple_acct/MYUSERNAME.session)
11-24 18:13:39 [pyicloud_ic3:1182] STAGE4  MYUSERNAME, Load Cookies File (/config/.storage/icloud3.apple_acct/MYUSERNAME)
11-24 18:13:39 [pyicloud_ic3:0776] STAGE4  MYUSERNAME, Authenticating with Token
11-24 18:13:39 [pyicloud_ic3:0851] STAGE4  MYUSERNAME, Authenticate with Token > Failed, Invalid Session Data
11-24 18:13:39 [pyicloud_ic3:0784] STAGE4  MYUSERNAME, Authenticating with Password SRP
11-24 18:13:39 [pyicloud_ic3:0992] STAGE4  MYUSERNAME, Authenticating with Password SRP, Send Credentials
11-24 18:13:39 [pyicloud_ic3:0202] STAGE4
🔺 MYUSERNAME, POST, REQUEST,  _AUTHENTICATE_WITH_PASSWORD_SRP/993
❗   items={'url': 'idmsa.apple.com/appleauth/auth/signin/init', 'retry': 0, 'json': None}
❗   data.items={'accountName': 'MYUSERNAME@…………', 'a': 'XXXX'}
11-24 18:13:40 [pyicloud_ic3:0259] STAGE4
🔻 MYUSERNAME, POST, RESPONSE, _AUTHENTICATE_WITH_PASSWORD_SRP/993 
❗   items={'code': 503, 'ok': False}
11-24 18:13:40 [pyicloud_ic3:0851] STAGE4  MYUSERNAME, Authenticate with Token > Failed, Invalid Session Data
11-24 18:13:40 [pyicloud_ic3:0823] STAGE4  MYUSERNAME, Authentication Failed, Connection Error, Secure Password Validation Data was not returned from Apple. ErrorCode-503
11-24 18:13:40 iCloud3 v3.1.3
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 655, in __init__
    self.authenticate()
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 824, in authenticate
    raise PyiCloudFailedLoginException(err_msg)
custom_components.icloud3.support.pyicloud_ic3.PyiCloudFailedLoginException: MYUSERNAME, Authentication Failed, Connection Error, Secure Password Validation Data was not returned from Apple. ErrorCode-503

11-24 18:13:40 [pyicloud_ic3:0242] STAGE4  APPLE ACCT SETUP > MYUSERNAME, Step-3, Setup PyiCloud, MYUSERNAME, Complete=False,
11-24 18:13:40 [pyicloud_ic3:0243] STAGE4  Apple Acct > MYUSERNAME, Login Successful
11-24 18:13:40 [start_ic3_co:0367] STAGE4  Apple Acct > MYUSERNAME, All Devices Located
11-24 18:13:40 [pyicloud_ic3:1543] STAGE4  MYUSERNAME, Create iCloud object MYUSERNAME)
11-24 18:13:40 [start_ic3………:1713] STAGE4  Apple Acct > MYUSERNAME, 0 of 0 tracked
`

**Comment by chupacabra71** [comment] 2024-11-24 11:54
apple must have changed something as i am seeing this as well.  I tried deleting my apple account, restarting HA, then re-adding it, but iCloud3 shows no devices registered.

**Comment by ninj4s** [comment] 2024-11-24 12:32
Can also confirm this exact issue:
11-24 13:07:45 CONFIG  username, Authentication Failed, Connection Error, Secure Password Validation Data was not returned from Apple. ErrorCode-503

**Comment by rononline** [comment] 2024-11-24 12:40
For me the same error. I changed my password twice now, deleted the .storage/icloud3 folder, removed the integration totally and reinstalled. Still the same error again.

**Comment by gcobb321** [comment] 2024-11-24 12:45
I am getting the same 503 Connection Error and have no idea why. 

It appears that Apple has made some changes once again, this time rejecting password requests made using the Secure Password Request protocol it implemented in October. I have changed the title to reflect the issue. 

There is nothing that can be done at this time but wait to see if they open it up again.

**Comment by JtwoA** [comment] 2024-11-24 15:32
Wow, yeah, this is a hard down.  Last time I managed to skate thru without impact but it's def very impacting now.

**Comment by Olsenoli** [comment] 2024-11-24 20:10
I have the same Problem. My Devices are not updating. And i dont get an new Verification Code.

**Comment by gcobb321** [comment] 2024-11-25 04:16
Some guys posted on the iCloud3 repo that downgrading to v3.0.5.9 let them get back up and running again. That uses the login routines before Apple broke everything at the end of October when they changed to the SRP password authentication protocol. 

At the moment, I am on a cruise ship off the west coast of Africa for another couple of weeks so an updated release is not going to happen until I get back. 

Plus, who knows how long before Apple changes it’s mind again and goes back to the new way of validating passwords. And I am also getting 503 errors on my real and test accounts with the v3.1.3 password routine, a 503 on my main account and on accounts that do not exist and cannot generate a verification code for my test account. My devices can not be located because I’m using Starlink, in airplane mode and have no cell service.

**Comment by JtwoA** [comment] 2024-11-25 04:55
Confirmed, rolling back to 3.0.5.9 allowed me to reauth against Apple and I have my devices back again.

Enjoy that trip, @gcobb321 !!

**Comment by dima-punkboy** [comment] 2024-11-25 11:05
> Confirmed, rolling back to 3.0.5.9 allowed me to reauth against Apple and I have my devices back again.
> 
> Enjoy that trip, @gcobb321 !!

For me too.

**Comment by groenmarsmannetje** [comment] 2024-11-25 11:14
I have downgraded to 3.0.5.9 and restarted Home Assistant. But I do not get Apple ID verification code dialog on my mobile device when I request it. Please share the exact steps that you have done for downgrading

**Comment by NR3Y** [comment] 2024-11-25 19:49
Yes, please detail the steps for rolling back. (Is this something we can download from HACS?)

**Comment by JtwoA** [comment] 2024-11-25 19:58
> Yes, please detail the steps for rolling back. (Is this something we can download from HACS?)

- Go to HACS.
- Find icloud3 developer edition
- Choose redownload from menu
- Choose the version noted above

**Comment by miraixyz** [comment] 2024-11-25 22:00
Got mine working again but had to go all the way back to 3.0.6b1.  Not perfect, but at least its tracking.

**Comment by JtwoA** [comment] 2024-11-25 23:12
> Got mine working again but had to go all the way back to 3.0.6b1. Not perfect, but at least its tracking.

Everyone else went back to 3.0.5.9

**Comment by gcobb321** [comment] 2024-11-26 05:47
@NR3Y 
Go to HACS and select the version you want to roll back to.

**Comment by Eifel-Joe** [comment] 2024-11-26 06:32
Confirmed. 3.0.5.9 is working again for me.

**Comment by joeu1998** [comment] 2024-12-02 15:48
I was having these same issues, I deleted the official integration, re-installed 3.0.5.9 via HACS, and am now seeing some weird behaviour. The Apple Account is authenticated successfully via 6-digit code, but both of my 2x tracked devices were showing up as being "FamShr Device: None". I deleted one and tried to re-add it as a new device - but I now just get the same error every time I try to re-add it: "Unknown error occurred". I get the same error when trying "UPDATE DEVICE" for the other device I'd been tracking, which I did not delete. Any ideas on how to get this working again?

<img width="772" alt="Screenshot 2024-12-02 at 15 47 06" src="https://github.com/user-attachments/assets/07983f9d-3139-4ca7-b819-7727241f9c6e">

**Comment by gcobb321** [comment] 2024-12-02 20:47
@joeu1998
Go to _Configure > Data Sources-Apple Accts & MobApp _ screen and enable iCloud/Family Sharing as a data source

**Comment by ronwar** [comment] 2024-12-04 09:16
When does the issue of login with the last version is going to be addressed ?

**Comment by gcobb321** [comment] 2024-12-04 11:16
@ronwar 
I am on a cruise ship off the west coast of Africa with starlink Internet service. I have not been able to log into any of my Apple accounts for 2-weeks and constantly get 503 errors trying to log in.   I return home on 12/10 and will address it then with an update that, hopefully, won’t take too long to get out. Stay tuned.

**Comment by ronwar** [comment] 2024-12-04 11:24
Appreciate your quick response

**Comment by naseemr** [comment] 2024-12-04 22:01
YES!  Confirmed, rolling back to 3.0.5.9 allowed me to reauth against Apple and I have my devices back again

**Comment by glenniana18** [comment] 2024-12-06 03:12
Thank you for this thread!  Rollback worked!

**Comment by ronwar** [comment] 2024-12-07 10:30
In addition to the logging issue (I've stayed in the current version until being corrected) ,I've upgraded to python 3,13 and got
the following (homeassistant version 2024.12.1) :
2024-12-07 12:00:48.381 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'icloud3': Unable to import component: No module named 'nacl'
  File "/home/homeassistant/.homeassistant/custom_components/icloud3/__init__.py", line 36, in <module>
    from .support.v2v3_config_migration import iCloud3_v2v3ConfigMigration
  File "/home/homeassistant/.homeassistant/custom_components/icloud3/support/v2v3_config_migration.py", line 113, in <module>
  File "/home/homeassistant/.homeassistant/custom_components/icloud3/support/config_file.py", line 42, in <module>
  File "/home/homeassistant/.homeassistant/custom_components/icloud3/support/start_ic3.py", line 65, in <module>
  File "/home/homeassistant/.homeassistant/custom_components/icloud3/support/mobapp_interface.py", line 20, in <module>
iCloud3EventLogCard._btnActionHandler (/local/custom_cards/icloud3-event-log-card.js:1876:37)
HTMLSelectElement.<anonymous> (/local/custom_cards/icloud3-event-log-card.js:978:62)
iCloud3EventLogCard._getButtonDevicename (/local/custom_cards/icloud3-event-log-card.js:1854:37)
iCloud3EventLogCard._nameButtonPress (/local/custom_cards/icloud3-event-log-card.js:1824:42)
HTMLUnknownElement.<anonymous> (/local/custom_cards/icloud3-event-log-card.js:973:66)
iCloud3EventLogCard._btnActionHandler (/local/custom_cards/icloud3-event-log-card.js:1876:37)
HTMLSelectElement.<anonymous> (/local/custom_cards/icloud3-event-log-card.js:978:62)

**Comment by gcobb321** [comment] 2024-12-23 15:32
This is fixed in v3.1.4

**Closed by gcobb321** 2024-12-23 15:32 UTC

**Comment by Holck1971** [comment] 2024-12-23 18:27
when will 3.14  released?

**Comment by gcobb321** [comment] 2024-12-23 18:33
@Holck1971 
I released it this morning on the iCloud3 Developers Repo. No one has reported any issues. I'll update the regular repo tomorrow. 

But here it is.

Unzip this into the icloud3 directo
[icloud3.zip](https://github.com/user-attachments/files/18232332/icloud3.zip)
ry and restart HA.

**Comment by Holck1971** [comment] 2024-12-23 18:52
thanks a lot, Gary :)

**Comment by Holck1971** [comment] 2024-12-23 19:07
is that another problem, or am I just too stupid and forgotten to activate something?
<img width="491" alt="SCR-20241223-rmgx" src="https://github.com/user-attachments/assets/ae9b2376-3607-44a4-b6fd-fea708e135a2" />

**Comment by gcobb321** [comment] 2024-12-23 19:19
Go to the _Configure > Other Parameters Menu > Waze_ screen. Check the Waze server location selection and make sure it is correct for your location. This is just a config issue to get the route info from Waze. Your devices are still being tracked.

**Comment by cedricdelecole** [comment] 2024-12-23 20:54
Upgraded to 3.1.3, can"t have it working ...
Vérification code I request is not sent to the device

![Screenshot_20241223_215244_Home Assistant](https://github.com/user-attachments/assets/8e3896f7-2108-4eff-a61f-50be350c6e0d)

**Comment by gcobb321** [comment] 2024-12-23 20:57
@cedricdelecole 
The new version is **v3.1.4**. v3.1.3 does not work..

**Comment by cedricdelecole** [comment] 2024-12-23 22:09
Ok, I will wait for it then ...

![Screenshot_20241223_230811_Home Assistant](https://github.com/user-attachments/assets/4b86323c-9166-4ca4-96ba-06e8f0ccb446)

**Comment by ronwar** [comment] 2024-12-24 10:43
> This is fixed in v3.1.4

Where docs folder goes ? (Near custom_component folder ?)

**Comment by JtwoA** [comment] 2024-12-24 13:54
> > This is fixed in v3.1.4
> 
> Where docs folder goes?(I think that is by mistake...). Succeed to log into the account (Gets code) but Get acount_name-> 0 of 0 iCloud devices tracked()

What "docs" folder?  

I just looked at what I pulled down as v3.1.4 and there's no "docs" folder.

**Comment by ronwar** [comment] 2024-12-24 16:22
> > > This is fixed in v3.1.4
> > 
> > 
> > Where docs folder goes?(I think that is by mistake...). Succeed to log into the account (Gets code) but Get acount_name-> 0 of 0 iCloud devices tracked()
> 
> What "docs" folder?
> 
> I just looked at what I pulled down as v3.1.4 and there's no "docs" folder.

Look here https://github.com/gcobb321/icloud3

**Comment by JtwoA** [comment] 2024-12-24 17:04
> > > > This is fixed in v3.1.4
> > > 
> > > 
> > > Where docs folder goes?(I think that is by mistake...). Succeed to log into the account (Gets code) but Get acount_name-> 0 of 0 iCloud devices tracked()
> > 
> > 
> > What "docs" folder?
> > I just looked at what I pulled down as v3.1.4 and there's no "docs" folder.
> 
> Look here https://github.com/gcobb321/icloud3

That's not part of the code.  You should be pulling it down from HACS at this point.  It's available, I just now checked.
