### ISSUE TITLE
Stuck on initializing and can't use event log card

### ISSUE THREAD

**Issue by broyuken** [gcobb321/icloud3_v3#43] opened 2023-01-17 18:48 UTC
Your latest update has gotten me to the point where I can pull in the devices and configure them, however ic3 still shows as initializing.
![image](https://user-images.githubusercontent.com/1593391/212985286-789a85a2-8c22-46ae-8fca-bf38553f29dd.png)

 I also can't use the event log reader card and get the following error in my HA logs.

```
2023-01-17 13:40:19.930 ERROR (MainThread) [frontend.js.latest.202301100] https://ha.broyuken.com/hacsfiles/icloud3/icloud3-event-log-card.js?v=1.000:1465:38 TypeError: can't convert undefined to object
2023-01-17 13:40:20.676 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
self._context.run(self._callback, *self._args)
File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 1027, in _read_ready
self._protocol.datagram_received(data, addr)
File "/config/custom_components/localtuya/discovery.py", line 70, in datagram_received
self.device_found(decoded)
File "/config/custom_components/localtuya/discovery.py", line 79, in device_found
self._callback(device)
File "/config/custom_components/localtuya/__init__.py", line 105, in _device_discovered
entry = async_config_entry_by_device_id(hass, device_id)
File "/config/custom_components/localtuya/common.py", line 126, in async_config_entry_by_device_id
if device_id in entry.data[CONF_DEVICES]:
KeyError: 'devices'
```

**Comment by gcobb321** [comment] 2023-01-17 18:59
Ahh, that error is coming from _localtuya_, not _icloud3_.
Do you have any errors in icloud3-debug.log or home-assistant.log?
Turn on 'debug' logging >iCloud3 > Configure > Event Log > Log Level, Then restart HA and see how far along in the startup process ic3 gets.

**Comment by broyuken** [comment] 2023-01-17 19:08
oops. sorry grabbed the wrong log.

```
Logger: frontend.js.latest.202301100
Source: components/system_log/__init__.py:256
First occurred: 2:06:47 PM (2 occurrences)
Last logged: 2:06:49 PM

https://ha.broyuken.com/frontend_latest/app.c86c7218.js:850:0 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "icloud3-event-log-card" has already been used with this registry
```

Thats the one I meant to copy. And I've made some progress. I now have my device trackers showing up, but they are showing up as device_tracker.brians_iphone_3 now. And I can't seem to get rid of the original device_tracker.brians_iphone from the 2.4 version of ic3

**Comment by broyuken** [comment] 2023-01-17 19:11
Also getting this error as well.

```
This error originated from a custom integration.

Logger: icloud3
Source: custom_components/icloud3/device.py:1382
Integration: iCloud3 Device Tracker (documentation, issues)
First occurred: 2:04:10 PM (162 occurrences)
Last logged: 2:10:50 PM

invalid literal for int() with base 10: 'not_set'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device.py", line 1382, in update_iosapp_battery_information
    self.dev_data_battery_level = int(entity_io.get_state(self.iosapp_entity[BATTERY_LEVEL]))
ValueError: invalid literal for int() with base 10: 'not_set'
```

**Comment by gcobb321** [comment] 2023-01-17 19:15
1. The _3 devicename suffix is caused by v2.4 owning device_tracker.brians_iphone. HA appends a number when another integration is using the same name. Comment out the platform: icloud3 statement in your configuration.yaml file so you are not running v2.4 and v3 at the same time. I should Update the docs for that.
2. The battery error is solved in b8a or b8b.

**Comment by broyuken** [comment] 2023-01-17 19:21
I did comment out the device tracker in configuration.yaml and I also commented out the /config/config_ic3.yaml file and rebooted but the entities are still there. 

And how do I fix the event log? I cleared my cache and also tried incognito mode, but the event log is still busted.

**Comment by gcobb321** [comment] 2023-01-17 19:24
Devices & Settings > Entities will list the entities. Click the box upper-left, then 3-dots upper right, select Remove.

Are any in use by iC3 v3 now? The iC3 integrations window shows a device and entity count.

**Comment by broyuken** [comment] 2023-01-17 19:28
![image](https://user-images.githubusercontent.com/1593391/212993806-145e247d-3ef9-466c-be8a-5c609732c454.png)
It's showing as read only and I don't have the ability to select or remove it.

**Comment by gcobb321** [comment] 2023-01-17 19:35
ic3 has brians_iphone_3, the Device tracker (which might be ic3 v2.4). And you are sure v2.4 is not running. Those devices are temporary and go away when it is not running. There would be info in the HA log file about that. Or is there another integration using brians_iphone?

An option might be to change the entity_name (select it, change name and update)?

**Comment by gcobb321** [comment] 2023-01-17 19:37
Also, once you get rid of the brians_iphone, go to ic3 devices and change the _3 name to one without a suffix. That should update the HA device registry

**Comment by broyuken** [comment] 2023-01-17 19:59
I'll try deleting the ic3 2.4 from hacs and see if that fixes it, but everything SHOULD be disabled. And I can't change the entity name of these temporary entities since they don't have a unique id.

**Comment by gcobb321** [comment] 2023-01-17 20:03
Deleting from hacs won't do anything.
You said you had both running at one time. All you need to do is wipe the icloud3 directory and install v3 there. v3 will get picked up like v2.4 was running, give a few messages and then start running v3. The brians_iphone must be coming from somewhere.
see if you have a 'known_devices.yaml' file.

**Comment by broyuken** [comment] 2023-01-17 20:13
After removing 2.4 from hacs completely, it looks like my _3 host is unavailable and ic3 v3 was renamed to brians_iphone. So it looks like they were both running at the same time somehow.

**Comment by gcobb321** [comment] 2023-01-17 20:16
Could v3 have been running in a different directory. The ha logs files show integrations right at the beginning. If you had an old one that is. Glad your are making progress, a little bit at a time

**Comment by broyuken** [comment] 2023-01-17 20:28
Another update, I had a custom resource for the event log card that I had to do a while back. I deleted that and the event log card works now too. At this point, I THINK all the issues are sorted. Will continue to test after I leave the house, but so far so good.

**Comment by gcobb321** [comment] 2023-01-17 20:37
I have changed the default directory for the evlog card from www/custom_cards to /www/icloud3 to try to make everything consistant

**Comment by broyuken** [comment] 2023-01-17 20:54
Good to know thanks. Now is b8b available on hacs? I have the latest from hacs and it's showing as 3.0.0b8a. Hacs itself is showing the version of 8427507

**Comment by gcobb321** [comment] 2023-01-17 20:57
No, the beta are not on hacs. I post a note when a new release is available on the first issues page with the names. It will point to the github Release for the latest release. Putting it on HACS at this stage is a pain and I dont want to mess with the 2.4.7 code. There are about 4500 people that have downloaded it from HACS and it's not ready yet.

**Comment by broyuken** [comment] 2023-01-17 21:08
You have 3.0.0b8a on hacs and it looks like its completely separate from 2.4. After you add it as a custom repository of course. Is there a non painful way to get the most recent version up there? Or do I need to just manually add it for now?
![image](https://user-images.githubusercontent.com/1593391/213012594-e1eadab3-340c-4d33-8c57-f4ea3a4fd370.png)

**Comment by gcobb321** [comment] 2023-01-17 21:09
Great. I didn't put it there

**Comment by broyuken** [comment] 2023-01-17 21:10
Ha, ok I guess I'll grab the most recent version and ftp it up there then

**Comment by broyuken** [comment] 2023-01-17 21:26
I'm on 8b now and I still see the following error in my logs.

```
This error originated from a custom integration.

Logger: icloud3
Source: custom_components/icloud3/device.py:1382
Integration: iCloud3 Device Tracker (documentation, issues)
First occurred: 4:25:16 PM (24 occurrences)
Last logged: 4:26:10 PM

invalid literal for int() with base 10: 'not_set'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device.py", line 1382, in update_iosapp_battery_information
    self.dev_data_battery_level = int(entity_io.get_state(self.iosapp_entity[BATTERY_LEVEL]))
ValueError: invalid literal for int() with base 10: 'not_set'
```

**Comment by gcobb321** [comment] 2023-01-17 21:33
Fixed in b9

**Comment by broyuken** [comment] 2023-01-17 21:59
Thanks, I'll keep my eye out for it. Also, thanks for the super fast responses.

**Comment by gcobb321** [comment] 2023-01-17 22:03
I'm just sitting at my computer writing code to be able to filter specific sensors from being created for a device.  Have a good day.

BTW - Where are you located?

**Comment by broyuken** [comment] 2023-01-17 22:06
I'm in the Boston area

**Comment by gcobb321** [comment] 2023-01-17 22:07
Cool. I grew up in Hamilton and went to college in Lowell decades ago.

**Closed** 2023-01-18 18:28 UTC

**Comment by broyuken** [comment] 2023-01-19 21:36
Nice! Where are you now?

**Comment by gcobb321** [comment] 2023-01-19 21:39
Vero Beach FL. East Coast, on a barrier island close 1/2 mi west of the ocean, Directly across the state from Tampa and 1.25hrs south of Cape Canaveral. We go out the back yard and Elon shoot off his rockets.

**Comment by broyuken** [comment] 2023-01-20 11:46
That’s awesome, my dad lives in Florida and we can go down the street and see launches too. It’s really cool to watch.

**Comment by broyuken** [comment] 2023-01-20 23:25
Definitely something strange going on here. My wifes iPhone won't get cleared out. I can't find any reference to it anywhere in the device or entity registries but it's still showing up. 

➜  .storage egrep device_tracker.britnis_iphone *
core.device_registry:            "device_tracker_britnis_iphone"
core.entity_registry:        "entity_id": "device_tracker.britnis_iphone_2",
core.entity_registry:        "entity_id": "device_tracker.britnis_iphone_3",
core.entity_registry:        "entity_id": "device_tracker.britnis_iphone_4",
core.restore_state:        "entity_id": "device_tracker.britnis_iphone_2",
lovelace:                        "entity_id": "device_tracker.britnis_iphone"
person:          "device_tracker.britnis_iphone",
➜  .storage

![image](https://user-images.githubusercontent.com/1593391/213822442-51a9f603-61d6-44fa-8f09-640b5b2bc808.png)
![image](https://user-images.githubusercontent.com/1593391/213822458-160c1c45-3f57-4b7d-a5f4-7b103ebf5f9c.png)
Where does 2.4 keep the entities it creates? Because I know they're created dynamically on startup. 

I have completely removed the icloud3 folder from custom_components and rebooted but it's still showing up.

**Comment by gcobb321** [comment] 2023-01-20 23:28
Did you look in the /config/known_devices.yaml file?

**Comment by broyuken** [comment] 2023-01-20 23:34
yea, it was in there, but I cleared it out, rebooted and the entity is still there.

**Comment by broyuken** [comment] 2023-01-21 01:37
A full reboot of the server seems to have cleared them out. just restarting HA didn't do it.
