### ISSUE TITLE
Trying to add apple account - “is not a valid option”

### ISSUE THREAD

**Issue by SigurdvanHauen** [gcobb321/icloud3_v3#351] opened 2024-11-04 18:31 UTC
I tried various things when the integration started misbehaving due to the login issue. 

I have tried installing the fix from the .zip folder from the other thread and now the newest from HACS. I have tried many things such as removing my old devices and deleting/re-installing the integration.

When I try to configure the integration by adding a new apple account I get the red error bar saying “is not a valid option”.

Is this a mistake from my part? Or is there a way where I can do a complete purge and fresh installation?

**Comment by gcobb321** [comment] 2024-11-04 18:43
What field is the error message above? If it’ss selection field, click it and what spite the options.?

Gary Cobb, aka geekstergary
________________________________
From: Sigurd van Hauen ***@***.***>
Sent: Monday, November 4, 2024 1:32:10 PM
To: gcobb321/icloud3_v3 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gcobb321/icloud3_v3] Trying to add apple account - “is not a valid option” (Issue #351)


I tried various things when the integration started misbehaving due to the login issue.

I have tried installing the fix from the .zip folder from the other thread and now the newest from HACS. I have tried many things such as removing my old devices and deleting/re-installing the integration.

When I try to configure the integration by adding a new apple account I get the red error bar saying “is not a valid option”.

Is this a mistake from my part? Or is there a way where I can do a complete purge and fresh installation?

**Comment by SigurdvanHauen** [comment] 2024-11-04 18:47
I have a screenshot here and the error message cannot be clicked:

![IMG_9971](https://github.com/user-attachments/assets/52ffe018-efd4-413b-b477-1c118be3862a)

**Comment by jspeckman** [comment] 2024-11-04 20:40
I get the same error on that screen with any option selected, including MENU.

**Comment by gcobb321** [comment] 2024-11-06 22:35
Looks like the Apple username/password is not available. Can you select Add and go to the next screen?

**Comment by nosar77** [comment] 2024-11-07 02:29
> Looks like the Apple username/password is not available. Can you select Add and go to the next screen?

Im having the issue as well, when you click add and go to the next screen thats the error you get.

**Comment by gcobb321** [comment] 2024-11-07 03:00
@nosar77 I would like to see your icloud3-0.log file to see what the Apple Acct config is. It is  _.storage/icloud3/configuration_. Send it to geekstergary@gmail.com. In hoping to get v3.1.1 out tomorrow but would like to see that to see what I can do.

**Comment by fear** [comment] 2024-11-08 05:45
The Problem is still there after the update to version 3.1

**Comment by nosar77** [comment] 2024-11-08 05:48
> @nosar77 I would like to see your icloud3-0.log file to see what the Apple Acct config is. It is  _.storage/icloud3/configuration_. Send it to geekstergary@gmail.com. In hoping to get v3.1.1 out tomorrow but would like to see that to see what I can do. 

Sorry I didn't send, I ended up deleting .storage before you responded and that fixed my issue. Somehow I think the config/login was corrupted and the only thing that fixed it was deleting icloud from .storage. hopefully that will point you in the right direction. Only clue I can give was, I might have messed it up by logging out or uninstalling and reinstalling the integration when the issues first started before u fixed it.

**Comment by gcobb321** [comment] 2024-11-08 11:03
@jspeckman
 The guys maintaining that SRP code have asked me to send them passwords that fail so they can fix their code.

 Instead of the log file,  if you would email your old password. Send it to geekstergary@gmail.com with the subject ‘SRP failed password’ do it doesn’t get lost with everything else. 

Thanks

**Comment by SigurdvanHauen** [comment] 2024-11-08 11:56
I also deleted the icloud3 from the .Storage folder and I can now login again. Cheers!

**Comment by gcobb321** [comment] 2024-11-08 12:27
@SigurdvanHauen 
There are iCloud3 2 directories in .storage. Which one did you delete?
- icloud3 (Configuration information)
- Icloud3.apple_acct (Apple cookies and login data)

**Comment by gcobb321** [comment] 2024-11-08 21:51
@fear 
What directory did you delete. See above note. I’m trying to see if it was the configuration or the Apple acct cookies and login session files. 
- If configuration, the Tools on the _Configure Settings > Update Devices_ screen can delete the devices.  
- If Apple acct folder, I’m wondering if just requesting another verification code, which deletes the login session files it’s enough so a newbie doesn’t have to get into .storage.

**Comment by nosar77** [comment] 2024-11-08 21:54
> @fear What directory did you delete. See above note. I’m trying to see if it was the configuration or the Apple acct cookies and login session files.
> 
> * If configuration, the Tools on the _Configure Settings > Update Devices_ screen can delete the devices.
> * If Apple acct folder, I’m wondering if just requesting another verification code, which deletes the login session files it’s enough so a newbie doesn’t have to get into .storage.


I deleted both because I couldnt even get the intergration to update devices afterwards, it wouldnt let me login, wouldnt let me send a verification code, it wouldnt let me update devices. I just kept getting unknown errors or random errors.

**Comment by fear** [comment] 2024-11-08 21:56
> @fear 
> 
> What directory did you delete. See above note. I’m trying to see if it was the configuration or the Apple acct cookies and login session files. 
> 
> - If configuration, the Tools on the _Configure Settings > Update Devices_ screen can delete the devices.  
> 
> - If Apple acct folder, I’m wondering if just requesting another verification code, which deletes the login session files it’s enough so a newbie doesn’t have to get into .storage. 

I deleted all files inside the folder after I did a backup. 😅

**Comment by SigurdvanHauen** [comment] 2024-11-08 21:57
> @SigurdvanHauen There are iCloud3 2 directories in .storage. Which one did you delete?
> 
> * icloud3 (Configuration information)
> * Icloud3.apple_acct (Apple cookies and login data)

I only deleted the iCloud3 not the .apple_acct.

It has worked flawlessly since and I am very happy for this awesome integration to work again. Thank you for your efforts and help!

**Comment by gcobb321** [comment] 2024-11-08 22:02
Can anyone send me a copy of the complete directory with all the files so I can see what was going on. Zip it. Ann a ‘.png’ as an extension to get by gmail filters and send to geekstergary@gmail.com 

Glad you guys got it going. Now to figure out what was causing the problems. 

Thanks again

**Comment by fear** [comment] 2024-11-08 22:30
> Can anyone send me a copy of the complete directory with all the files so I can see what was going on. Zip it. Ann a ‘.png’ as an extension to get by gmail filters and send to [geekstergary@gmail.com](mailto:geekstergary@gmail.com)
> 
> Glad you guys got it going. Now to figure out what was causing the problems.
> 
> Thanks again

done

**Comment by gcobb321** [comment] 2024-12-23 15:42
This is probably fixed in v3.1.4. Create a new issue if you encounter this problem again.

**Closed by gcobb321** 2024-12-23 15:42 UTC
